### ISSUE TITLE
[Bug] GifCaptioner cannot be compiled.

### ISSUE THREAD

**Issue by minnieoo** [TheLazySquid/DiscordGifCaptioner#6]
### discord version: 
stable 303105 (1897d8a) 
Host 1.0.9151 x64 (48891) 
Build Override: N/A Windows 11 64-bit (10.0.22631)

### plugin version
v0.1.3

### better discord version
core v1.10.2

### the issue
i am notified by better discord that GifCaptioner cannot be compiled, and the plugin can no longer be enabled. here is the console error
```
TypeError: Cannot read properties of undefined (reading 'default')
    at new module.exports (betterdiscord://plugins/GifCaptioner.plugin.js:2202:93)
    at N.initializeAddon (betterdiscord/renderer.js:5:27014)
    at N.loadAddon (betterdiscord/renderer.js:5:6406)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)
```

### screenshots
![image](https://github.com/TheLazySquid/DiscordGifCaptioner/assets/137783738/4b66a23d-4c1c-4469-8415-77086bb9e80d)

**Comment by TheLazySquid** [comment]
There was a discord update that broke a lot of plugins/themes, but it should be working now. You'll need to download the plugin from this repo until the changes are accepted by the official betterdiscord repo.
